### ISSUE TITLE
💡 [FEAT] Make pending overdue and done as default in right status bar

### ISSUE THREAD

**Issue by sathishmanohar** [dooit-org/dooit#104]
Right now the default installation has username and time which isn't very useful but if there is count of pending overdue and done in there as default as shown in the screenshots in the project. It'll be far more useful.

![image](https://user-images.githubusercontent.com/270991/225896197-fbe4ee0a-cf71-4950-bb89-d1a71180d0d6.png)

If possible it can be made dynamic by changing the numbers as

In dashboard - count all tasks
In workspace - count workspace tasks
In task with sub tasks - count the sub tasks

etc.

**Comment by kraanzu** [comment]
This is something I thought of. I'm working on some optimizations so the parsing would be fast and the user would not feel the app being sluggish :smile:

**Comment by kraanzu** [comment]
Closing this as we now have [Widgets](https://dooit-org.github.io/dooit-extras/widgets/clock.html)! 

Check out some of the [Example Configs](https://dooit-org.github.io/dooit-extras/configs/config1.html)
