### ISSUE TITLE
💡 [FEAT] Query TODOs from the commandline

### ISSUE THREAD

**Issue by FelixKratz** [dooit-org/dooit#130]
I think it would be great if there was a commandline interface to dooit, with which the todos could be printed to stdout.

My use case would be that I would like to display the todo that is due next in my global system status bar along with some other todo metadata.

Something like `dooit --list all --sort due --format "%n %d %t"` would be a great addition. The command should then only output the relevant todos to stdout in the specified format (e.g. `%n` would be the format sequence for the title of the todo, `%d` would be the due date and `%t` would be the tags of the todo item etc.) and sorted by the flag supplied in `--sort`.

**Comment by kraanzu** [comment]
Hey!

> My use case would be that I would like to display the todo that is due next in my global system status bar along with some other todo metadata.

Maybe you can currently use python scripts for that?

This is a great idea tho. Altho I am a bit confused about the implementation part since it has a pretty complex structure :(

**Comment by maulik13** [comment]
@kraanzu thanks for making this app. Any way you can show an example of a Python script that can query data? 
Thanks!

**Comment by kraanzu** [comment]
Hi @maulik13 , You can check out [Backend API](https://dooit-org.github.io/dooit/backend/introduction.html) from the docs.

If you need any assistance, feel free to open a discussion :)

As for the initial idea of this issue thread, maybe I can create a separate parser just for this and integrate it with dooit. For now, I'll close this issue. 

Note: You still can run custom python scripts for regularly used queries :D
