### ISSUE TITLE
[BUG] day is out of range for month error when switching date style if date is last day of a month

### ISSUE THREAD

**Issue by hansemschnokeloch** [dooit-org/dooit#171]
**Describe the bug** 🐛
If a due date is the last day of a month, switching date style raise a ValueError: days is out of range for month error

**To Reproduce** 🐣
1. Enter a due date that is the last day of a month (example: 30-06-2024)
2. Switch due date style with `D` key (shift d)
3. See error

**Screenshots** 🧐
![Capture d’écran du 2024-02-09 11-04-45](https://github.com/kraanzu/dooit/assets/792829/c3d76666-ded2-4ab0-870a-6aeaa800ce48)

**Desktop (please complete the following information):**  🤖
 - OS: NixOS
 - Version 2.2.0

**Comment by kraanzu** [comment]
Ah, edge case. Thanks for opening the issue! I'll look into it :)

**Comment by kraanzu** [comment]
Closing this as this should be fixed.
