### ISSUE TITLE
[BUG] Sort mode broken, when canceling with <ctrl+s> instead of <esc>

### ISSUE THREAD

**Issue by LanceTheDev** [dooit-org/dooit#175]
**Describe the bug** 🐛
When I cancel the sort mode with <ctrl+s> instead of <esc> key, it's not toggleable anymore afterwards. I need to restart the application to make it work again.

**To Reproduce** 🐣
1. Open sort menu by pressing <ctrl+s>
2. Cancel sort menu by pressing <ctrl+s> instead of <esc>
3. Menu closes, but mode stays is "SORT"

**Expected behavior**  🤔 
Mode should switch back to NORMAL and sort menu should be toggleable afterwards

**Desktop (please complete the following information):**  🤖
 - OS: Ubuntu 22.04.3 LTS
 - Version: 2.2.0

**Comment by kraanzu** [comment]
It's weird behavior indeed. Fortunately `escape` works.
I'll look into this

**Comment by LanceTheDev** [comment]
I would like to take a look into that issue as well. I believe my python skills should at least be good enough to identify the root cause. If you agree, I will take a look in the coming days and report back.

**Comment by kraanzu** [comment]
Sure thing. The code might be a bit messy (I'm planning on a re-work) so feel free to ping me for any pointers

**Comment by LanceTheDev** [comment]
I haven't had the time yet, to tackle this and wanted to reaffirm you of my willingness to do so. Next week, starting on wednesday, I will take a few days off of work and will make sure, to start with it :+1:

**Comment by kraanzu** [comment]
Thanks for the confirmation! Do give me a heads up if you start with anything :)

>  I will take a few days off of work and will make sure, to start with it 👍

Ay! Don't stress too much about it man. And days off are for relaxing :sunglasses:

**Comment by kraanzu** [comment]
Closing this as stale, `escape` is now the only key to close sort menu :)
