### ISSUE TITLE
[BUG] On M2 mac dooit is taking 15% of CPU

### ISSUE THREAD

**Issue by albinocordeiro** [dooit-org/dooit#177]
**Describe the bug** 🐛
Just by having dooit running on my terminal it takes more CPU than any other app I have open.

**To Reproduce** 🐣
1. Using the Warp.app terminal
2. Start dooit and add tasks with expiry dates etc.
3. Check CPU usage

**Expected behavior**  🤔 
To have zero CPU usage when I'm not using it.

**Screenshots** 🧐

**Desktop (please complete the following information):**  🤖
 - OS: [e.g. Mac OS
 - Version 2.2.0

**Additional context** 📝

**Comment by kraanzu** [comment]
Hmm.. weird
can you run other apps of textual?

Example:

```
textual colors
```

```
python -m textual
```

**Comment by albinocordeiro** [comment]
Sure, how do I install textual?

**Comment by albinocordeiro** [comment]
I ran `python -m textual` and the sample app took negligible CPU.

**Comment by kraanzu** [comment]
Closing this in favor of https://github.com/dooit-org/dooit/issues/183, Can you install the latest version and lemme know again? Thanks!
