### ISSUE TITLE
💡 [FEAT] Add warning/confirmation when deleting projects

### ISSUE THREAD

**Issue by silentjay** [dooit-org/dooit#187]
Thought I was deleting a todo item, not realising I was in the projects context and accidentally nuked a project instead. I think it should be more obvious when you're deleting projects, maybe with a confirmation box or warning.

**Comment by kraanzu** [comment]
Hi, nice suggestion. Ideally I think it'd be best to show a yes/no button in the bar?

Also quick tip: deleting an item copies it to the clipboard and you can press `p` to paste it again :)

**Comment by kraanzu** [comment]
Hi @silentjay, just to let you know that this implementation would require some work to modify the current main branch, so it wont be published until the new release (I've writing it from scratch to make it more robust + faster)

Here's a sneak of the implementation when it comes out, ignore the bars and the alignment, I'll be finishing them this week!



https://github.com/user-attachments/assets/67382cf4-19ea-4547-b73e-cde102f0d517

**Comment by silentjay** [comment]
@kraanzu looks like a great little UI improvement, looking forward to the next release!

**Comment by kraanzu** [comment]
Hi again @silentjay, dooit now asks for confirmation before deleting, this behaviour can be changed in the config
Check out [show_confirm](https://dooit-org.github.io/dooit/configuration/vars.html#editable-show-confirm)
