### ISSUE TITLE
[BUG] Tried to insert a widget with ID, but a widget already exists with that ID in this list of childen.

### ISSUE THREAD

**Issue by AmberLehmann** [dooit-org/dooit#189]
Upon attempting to sort my tasks by date, I get the following error seen in the screenshot below. Note, I have 7 tasks in my list, and the NodeList shows 8 with two duplicates.
 
I would expect the list to be sorted but, instead, the program crashes.
![image](https://github.com/user-attachments/assets/be4ec564-636b-4bcb-9672-cced690eadb0)

Desktop Info: 
 - OS: NixOS
 - Version 24.11

I am unsure as to why this may be. I installed the program through the nixpkgs ecosystem.

**Comment by kraanzu** [comment]
Pretty weird, Can you share your db file? If not, can you tell me the steps to replicate?  I cant seem to do so

**Comment by AmberLehmann** [comment]
Sorry, I am unsure where the db file is found. If you can direct me to the location I would be happy to share.

Steps to replicate:
Create a workspace
Populate the workspace with 7 tasks with differing due dates not in order.
CTRL + S, J, Enter

**Comment by kraanzu** [comment]
Hi, It should be in this folder:

`~/.local/share/dooit/`

**Comment by AmberLehmann** [comment]
This file shows 7 unique tasks, with unique uuids wrapped in a workspace. Some tasks have the same `due` fields. Forgive me for not sharing the contents of the file. When dooit crashes, the third tasks with the lowest value for date is duplicated.

I feel hesitant to share my task due dates for privacy reasons. I hope you understand, and my descriptions are sufficient.

**Comment by silentjay** [comment]
Could you make a copy of the db file and change the task descriptions to "redacted" or something before sharing? Happy to help try and debug

**Comment by AmberLehmann** [comment]
`- uuid: workspace_023d13fb-c686-4fdf-b642-be9b0cbe34b6
  description: First
  todos:
  - - uuid: todo_3864cbee-dd30-4d9b-a261-b59a8a09fee0
      status: PENDING
      urgency: 1
      description:  REDACTED1
      due: '1727841600.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_73b70d1c-d645-4216-bbb2-314a67361a24
      status: PENDING
      urgency: 1
      description: REDACTED2
      due: '1727236800.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_7f7b7d82-3968-4979-b670-7fd9f0f16a80
      status: PENDING
      urgency: 1
      description: REDACTED3
      due: '1726977600.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_b6d0c057-9399-43f2-94e1-53cd741f4359
      status: PENDING
      urgency: 1
      description: REDACTED4
      due: '1727323200.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_e99943f4-b1b4-40bf-a9ad-a24ba36f2616
      status: PENDING
      urgency: 1
      description: REDACTED5
      due: '1727236800.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_55150e32-f9c7-43f4-9524-dd08876f770a
      status: PENDING
      urgency: 1
      description: REDACTED6
      due: '1727064000.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_2b77e424-e932-4abc-8b38-0b9b5f7ba5d5
      status: PENDING
      urgency: 1
      description: REDACTED7
      due: '1727323200.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_ee39f621-4a03-4fc2-86ef-13e05bc59a38
      status: PENDING
      urgency: 1
      description: REDACTED8
      due: '1727841600.0'
      effort: ''
      recurrence: ''
  - - uuid: todo_eec9a9d4-e76f-4149-aa5a-fe869942f72a
      status: PENDING
      urgency: 1
      description: REDACTED9
      due: '1729569600.0'
      effort: ''
      recurrence: ''
  workspaces: []`

I have since added two tasks but the issue is the same.

**Comment by silentjay** [comment]
@AmberLehmann thanks. I've tested your db file and works fine this end, can sort by due date and every other sort option, no errors

![image](https://github.com/user-attachments/assets/cc7ae5cd-bd56-4c9e-9a5b-c07f21fee2ce)

Are you on the latest version? How did you install dooit?

**Comment by AmberLehmann** [comment]
Through nixpkgs.

**Comment by kraanzu** [comment]
I highly doubt that nix has anything to do with this but I'll try to replicate it. Thanks for sharing

**Comment by kraanzu** [comment]
I found the issue: So the main branch for dooit uses textual 0.47 (the underlying TUI library) but nixpkgs stable has 0.72 (0.79 on unstable), which doesn't work.  Perhaps an overlay should do the trick? Im pretty new to nixos myself so not entirely sure but I'll try to write it (or perhaps you have a quick solution for this @AmberLehmann ?)

**Comment by silentjay** [comment]
@AmberLehmann @kraanzu how about uninstalling and reinstalling via pipx?

**Comment by kraanzu** [comment]
yep pipx can be a good solution, not sure if nixos would permit that or not. Lemme try

**Comment by kraanzu** [comment]
This should be fixed with the newer version! Feel free to re-open if this still persists for you

---------

Also lemme know your thoughts on the docs if its too confusing to understand, etc
Thank you for trying out dooit <3
