### ISSUE TITLE
[FEAT] Move config location to a cli flag

### ISSUE THREAD

**Issue by zachvalenta** [dooit-org/dooit#195]
Per [docs](https://github.com/kraanzu/dooit/wiki/Configuration):

> The config location should be present in you local config dir Run this command to print the directory:

```python
python -c "import appdirs; print(appdirs.user_config_dir('dooit'))"
```

This code block, when runs, throws the following error:

```python
python -c "import appdirs; print(appdirs.user_config_dir('dooit'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'appdirs'
```

I'm using macOS 13.4 and installed `dooit` via pipx.

**Comment by kraanzu** [comment]
I see. This is because you installed via pipx which installs everything in an isolated space. I should move this to a CLI flag instead

In macOS, I think this should be at `~/.config/dooit`

**Comment by zachvalenta** [comment]
It actually gets written to `/Users/$USER/Library/Application Support/dooit`.

**Comment by kraanzu** [comment]
Oh haha. I thought linux and mac are the same. Thanks for pointing that out, also I'll include it as a flag now in the cli

**Comment by zachvalenta** [comment]
`/Users/$USER/Library/Application Support/` is pretty common on macOS, used by:

* VS Code
* Brave
* harlequin
* iTerm
* pipx
* zoxide

among the tools I have on my machine.

Still, far more in `/Users/$USER/.config` and a better location IMO, but clearly no consensus on the matter.

**Comment by kraanzu** [comment]
Dooit now has a `config-loc` flag to print config location!
