### ISSUE TITLE
💡 [FEAT] Save task status changes to data file immediately on change

### ISSUE THREAD

**Issue by silentjay** [dooit-org/dooit#196]
I've written a little script to extract tasks from the yaml data file to a text file which is then in turn read by conky so I have a constant transparent task list on my desktop. Works great to keep me on track when i'm not in the terminal. The only issue is that dooit doesn't save changes to a tasks status until another action action is performed e.g. adding or deleting a separate task, so updates to my tasks status in conky won't show immediately.

Is there any chance that task status changes are saved immediately to the data file?

**Comment by kraanzu** [comment]
Hi, it was weird behavior. It should be ok with the newer version.
You should check out [backend docs](https://dooit-org.github.io/dooit/backend/introduction.html)

Also, I'll be happy to assist you if you need anything for the script. I'll close this issue for now, if you need any help, feel free to open a discussion :)

**Comment by silentjay** [comment]
Thanks had a quick play around with the new version, looks good. To configure dooit using the new API is this code now placed in the previous config file? The docs don't mention this.

I've reverted back to 2.2.0 for now until I have time to sort the config out and update my script to get the todos from the new API instead of direct from the previous versions YAML file.

**Comment by kraanzu** [comment]
Oh True, I did add a flag. I'll update this. Thank you
