### ISSUE TITLE
💡 [FEAT] Possibility to toggle visibility of Workspaces pane

### ISSUE THREAD

**Issue by maulik13** [dooit-org/dooit#197]
**Is your feature request related to a problem? 😢 Please describe.** 
No a problem really. But, it would definitely help. 

**Describe the solution you'd like**   🤔
A shortcut to toggle Workspaces pane. 

**Describe alternatives you've considered**  🧐
Not sure if there is any. 

**Additional context** 📝
I like to keep my task list on the side in a small window. Having Workspaces open takes away some space and it is not usable in small windows.
![image](https://github.com/user-attachments/assets/a079c69c-7e72-4bd1-b327-31d144fa22e7)

**Comment by kraanzu** [comment]
Btw, I also saw your comment on the other thread asking about the API, it's changed drastically from v2 and should be much easier to play around with. will have a proper documentation

**Comment by maulik13** [comment]
Hey @kraanzu  that looks exactly what I want 😄. I am really looking forward to it! Awesome that you responded so quickly. 

I saw the API docs and was wondering about playing around with it. But I can wait a bit for v2 👍

**Comment by kraanzu** [comment]
Hi @maulik13 !

A newer version has been released so you can check it out!
Also, you can hide the workspaces using [this script](https://dooit-org.github.io/dooit-extras/scripts/toggle_workspaces.html#toggle-workspaces)

Also lemme know your thoughts on the docs if tits too confusing to understand, etc
