### ISSUE TITLE
[BUG] ValueError in Dooit: SCREENS Contains Instance Instead of Callable Screen Type

### ISSUE THREAD

**Issue by zx0r** [dooit-org/dooit#198]
Hi bro)
 
Describe the bug 🐛
Dooit Initialization Error: SCREENS Configuration Incorrectly Uses Instance

```fish
Desktop Environment 👽
 - OS: Gentoo Base System release 2.16
 - Linux unixp0rn 6.11.5-gentoo-x86_64
 - XDG_SESSION_TYPE: wayland
 - Window Manager: Hyprland
 
# sudo -e /usr/lib/python3.12/site-packages/dooit/ui/tui.py
# error 🚫
 ------------------------------------------------------------------------------
# class Dooit(App):
#     CSS = screen_CSS
#     SCREENS = {
#         "main": MainScreen(name="main"),
#         "help": HelpScreen(name="help"),
#     }
# fix ✅
 ------------------------------------------------------------------------------
class Dooit(App):
    CSS = screen_CSS
    # Reference the screen classes without instantiating them
    SCREENS = {
        "main": MainScreen,  # Use the class directly
        "help": HelpScreen,  # Use the class directly
    }
```
_**Additional context** 📝_
The error traceback indicated that the issue was caused by incorrectly instantiating the screens within the SCREENS dictionary. To fix this, the SCREENS declaration was modified to only include the class references without instantiation:
```fish
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/dooit", line 5, in <module>
    from dooit.__main__ import main
  File "/usr/lib/python3.12/site-packages/dooit/__main__.py", line 3, in <module>
    from dooit.ui.tui import Dooit
  File "/usr/lib/python3.12/site-packages/dooit/ui/tui.py", line 17, in <module>
    class Dooit(App):
  File "/usr/lib/python3.12/site-packages/textual/message_pump.py", line 109, in __new__
    class_obj = super().__new__(cls, name, bases, class_dict, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/textual/app.py", line 790, in __init_subclass__
    raise ValueError(
ValueError: SCREENS should contain a Screen type or callable, not an instance (got instance of MainScreen for 'main')
```
_**Screenshots** 📺_

![captura-2024-11-05-1730815042](https://github.com/user-attachments/assets/ae680bea-553a-4a3c-b907-90c91091e4d9)
![captura-2024-11-05-1730816716](https://github.com/user-attachments/assets/1f976afc-4c18-4b30-a36e-f26fd419fd31)
![captura-2024-11-05-1730815148](https://github.com/user-attachments/assets/ca867647-efdc-4f4d-bfc3-a25b4a8235f0)

**Comment by kraanzu** [comment]
Hi @zx0r , Yes The current version uses a very old release of Textual, the underlying TUI library hence the issue. How are you installing `dooit`? The version needs to be pinned if you're using distro-specific package manager. No idea about gentoo sorry, I guess it was `emerge` ? Can you share some details?

Plus, I'll make a new release tomm so things should sort out when the package is updated:)

**Comment by zx0r** [comment]
Portage package manager priority)

![captura-2024-11-05-1730831026](https://github.com/user-attachments/assets/a9273e0a-1ba2-4f3b-a128-edf6d9da5be6)

**Comment by kraanzu** [comment]
Hi again @zx0r ! Sorry totally forgot about this, I've released a newer version, are you familiar with gentoo packaging?

**Comment by kraanzu** [comment]
Hi @henri-gasc!

Look like you made the contribution to GURU for dooit. Can you update to the latest version? I can help if required :)

**Comment by henri-gasc** [comment]
No need for help, I will update it soon. I did not see there was an update

**Comment by kraanzu** [comment]
Thank you! I'll also release a new version in a few hours with a patch bump.

**Comment by henri-gasc** [comment]
I pushed the update, you can close this issue

**Comment by kraanzu** [comment]
@zx0r, please double check from your side and feel free to open any other issues if you have :)
