### ISSUE TITLE
[BUG] Error during migration from V2

### ISSUE THREAD

**Issue by fdufnews** [dooit-org/dooit#201]
**Describe the bug** 🐛
Migrating from V2 gives an error
During migrate I have the following in my console
```
[+] Migrating` from v2...
[+] Checking for old data
[+] Found old data Converting
Database already exists. Do you want to overwrite it? (y/n): y
[!] Error converting data: 'dict' object has no attribute '_sa_instance_state'
```
**To Reproduce** 🐣
From a configuration previously using dooit v2
1. enter dooit migrate

**Expected behavior**  🤔 

**Screenshots** 🧐

**Desktop (please complete the following information):**  🤖
 - OS: Linux 6.6.51+rpt-rpi-v8 aarch64
 - python 3.11.2

**Additional context** 📝

**Comment by kraanzu** [comment]
Hmmm..pretty werid. Lemme doube check. Did it contain a lot of todos?

**Comment by fdufnews** [comment]
Here find my configuration file and the todo.yaml
[filesl.zip](https://github.com/user-attachments/files/17691950/filesl.zip)

**Comment by kraanzu** [comment]
Oh..Nice...I was going to ask for a redacted one but hey, thanks

**Comment by kraanzu** [comment]
> For information, it behaves the same under Ubuntu and Python 3.12

yea yea, it has something to do with the SQL lib

**Comment by kraanzu** [comment]
Hi @fdufnews, can you try again with the latest version? Thanks

**Comment by fdufnews** [comment]
Yes, just getting the last release and migration was successful
Thank you very much
