### ISSUE TITLE
[BUG] Crash after deleting workspace or todo item

### ISSUE THREAD

**Issue by nguyentran0212** [dooit-org/dooit#205]
**Describe the bug** 🐛

Deleting, adding, and deleting a todo item or workspace will crash the app.

**To Reproduce** 🐣
1. Create a workspace / todo item (press a, input the title, press esc)
2. Delete the created item (press xx, press y)
3. Create a new workspace / todo item (press a) => **The title of the previous workspace item would appear.** Upon pressing esc, an error message would flash up at the bottom of the screen. 
4. Delete the newly created item (press xx, press y) => **Dooit crashes**

**Expected behavior**  🤔 

Not crashing.

**Screenshots** 🧐

Part of the trace stack:

<img width="1700" alt="Screenshot 2024-11-14 at 12 13 06 pm" src="https://github.com/user-attachments/assets/e38ab3dc-60ec-41b7-adc4-9a8b795ec264">

**Desktop (please complete the following information):**  🤖
 - OS: MacOS 14.3.1
 - Version Dooit 3.0.2

**Comment by kraanzu** [comment]
Yes I just noticed it yesterday if you do it fast enough. Thanks for opening this

**Comment by kraanzu** [comment]
Should be fixed with the latest update now :)
