### ISSUE TITLE
[BUG] Crash on start up

### ISSUE THREAD

**Issue by nguyentran0212** [dooit-org/dooit#207]
**Describe the bug** 🐛
Dooit 3.0.3 crashes on start up.

**To Reproduce** 🐣
1. Type dooit in terminal

**Expected behavior**  🤔 
Not crashing

**Screenshots** 🧐
![241118_11h14m37s_screenshot](https://github.com/user-attachments/assets/1e0ad55e-9bf4-4977-b3df-d108824c02d5)

**Desktop (please complete the following information):**  🤖
 - OS: ArchLinux
 - Kernel 6.11.8-arch1-2

**Additional context** 📝
Package installed from AuR using yay.

**Comment by kraanzu** [comment]
That is weird. Did you install from the AUR?

**Comment by nguyentran0212** [comment]
Yup. I just run pacman - Syu and then update the dooit package from AUR.

**Comment by kraanzu** [comment]
Alright. Thanks for confirming, I'll update this in an hour or so

**Comment by kraanzu** [comment]
Hi @nguyentran0212, 

should be fixed now. Can you re-sync the packages and check again? Thanks :)

**Comment by nguyentran0212** [comment]
@kraanzu thanks for the quick response! I can confirm that version 3.0.4 works without any problem.
