### ISSUE TITLE
No such column: recurrence

### ISSUE THREAD

**Issue by sevennotfound** [dooit-org/dooit#212]
I'm sure this isn't a bug, but it's just me being dumb.
When I try to add recurrence it just says `no such column: recurrence`
I'm sure there's some way to add it, but I couldn't find anything in the docs.
Thanks!

**Comment by kraanzu** [comment]
Hi @sevennotfound,

By default I excluded the recurrence column so it doesn't show up. You can tweak what columns you want in dooit
Check [this](https://dooit-org.github.io/dooit/configuration/layout.html#how-to-use) out!
