### ISSUE TITLE
[Question]  How to change the Effort? 

### ISSUE THREAD

**Issue by KierPrev** [dooit-org/dooit#213]
When pressing 'e', it  appears "No such column effort"

dooit-extras is already installed with pip.

**Comment by kraanzu** [comment]
Yes a lot of people are finding it confusing, I should add all the columns by default

You can use [layouts](https://dooit-org.github.io/dooit/configuration/layout.html#how-to-use)  to customize which columns you'd like to have.

I'll close this issue but feel free to ask me if anything's confusing :)
