### ISSUE TITLE
[BUG] Crashes when no workspaces/items exist due to CSS

### ISSUE THREAD

**Issue by rohrsben** [dooit-org/dooit#215]
**Describe the bug** 🐛
If there are no workspaces already existing (typically on first run) dooit crashes due to a css error:

```
╭─ Error at /home/error/.cache/dooit/dooit.tcss:38:─╮
│    36 ModelTree {                                 │
│    37 │   background: $background1;               │
│ ❱  38 │   background-tint: white 0%;              │
│    39 │   color: $foreground3;                    │
│    40 │   border: $border_type $background3;      │
╰───────────────────────────────────────────────────╯
   Invalid CSS property 'background-tint'. Did you   
   mean 'background'?
```

This does not occur if you have a workspace created; e.g., edit `dooit.tcss` and remove line 38, relaunch and create a workspace, then continue on. Interestingly, the app looks much better without the line present: more (and more cohesive) colors are getting applied. If you add the line back in *and* have a workspace present, the app looks worse (aka less cohesive) but at least launches.

The crash starts happening again if you delete all workspaces. Or something. Maybe if you have just one empty workspace that still crashes? This part has been a bit hard to figure out.

**To Reproduce** 🐣
1. Freshly install dooit
2. Try to run dooit
3. See error

**Expected behavior**  🤔 
Dooit launches normally.

**Screenshots** 🧐

**Desktop (please complete the following information):**  🤖
 - OS: NixOS 
 - Version: Unstable

**Additional context** 📝
I have dooit installed via flake, and am running the most recent version. Notably I could not get the dooit-extras overlay working though, and do not have it installed.

**Comment by kraanzu** [comment]
Hi @rohrsben, 

Ah shoot, looks like the underlying library has not been updated in the nixpkgs. I'll make a PR then
Also, about dooit-extras, can you share your flake so I can check it out?

**Comment by kraanzu** [comment]
OK so I found out that this is already in progress.
See [here](https://nixpk.gs/pr-tracker.html?pr=356997)

Until then I guess you'll have to wait :(
It should be merged quickly though. I'll keep track of this

**Comment by rohrsben** [comment]
Ok, no worries. As for the overlay, here's the relevant parts of my config:

```nix
# flake.nix
dooit.url = "github:dooit-org/dooit";
dooit-extras.url = "github:dooit-org/dooit-extras";
```

```nix
# dooit.nix, imported in hm
# *this does not work*
{ inputs, pkgs, ... }:

{
    imports = [
        inputs.dooit.homeManagerModules.default
    ];

    nixpkgs.overlays = [ inputs.dooit-extras.overlay ];

    programs.dooit = {
        enable = true;
        extraPackages = [
            pkgs.dooit-extras
        ];
    };
}
```
I simply commented out the nixpkgs and extrapackages parts, which did work.

**Comment by kraanzu** [comment]
OK I can also confirm that something is wrong with the overlay, I'll update you with a fix but you can use this alternatively:

```nix
extraPackages = [inputs.dooit-extras.packages.x86_64-linux.default];
```

**Comment by rohrsben** [comment]
Marking this as closed seeing as the nixpkgs merge landed. As far as I can tell it's now fully usable, but dooit-extras is still having an issue. I'm not *personally* too concerned with themeing, but I'll make a new issue since nix is giving me an actual error now.
