### ISSUE TITLE
[BUG] Dooit-extras fails to build on NixOS

### ISSUE THREAD

**Issue by rohrsben** [dooit-org/dooit#216]
**Describe the bug** 🐛
Dooit-extras fails to build when installed via flake (via home-manager, though in theory that shouldn't matter?). Seems to be some sort of input mismatch, but I grepped the `dooit` repo for any part of the hash (in case the issue was in a lock file somewhere) and got no matches.

As far as I can tell, this is the relevant error. Nix can be... difficult to diagnose.
```
error: hash mismatch in fixed-output derivation '/nix/store/rx0j4m2li1j399prl2yc4i357wzwhq5n-source.drv':
         specified: sha256-dTq00DlZSuRAhDFETpvZc9904nELp891WUFYLt3IH8g=
            got:    sha256-ZBzzH8k4oC3ovLF9+9rzzFZaDDoOvcbX5NCh1WBedK4=
```

**To Reproduce** 🐣
1. Attempt to install dooit-extras.
2. See error

**Expected behavior**  🤔 
Dooit-extras installs. Though I admit I'm not sure what its supposed to actually do.

**Desktop (please complete the following information):**  🤖
 - OS: NixOS
 - Version: Unstable
 
**Additional context** 📝
This is specifically in regards to `extraPackages = [ inputs.dooit-extras.packages.x86_64-linux.default ];`. Installing it as an overlay also fails, but I don't (and have never) use overlays in my config so I don't really understand what they do or how.

**Comment by kraanzu** [comment]
Hi @rohrsben, dooit-extras is a collection of pre-defined stuff to customize dooit. 
Heres the documentation: https://dooit-org.github.io/dooit-extras/

**Comment by kraanzu** [comment]
I'm still working on docs to make it much easier to use this stuff. Hopefully will make a new release soon
