### ISSUE TITLE
💡 [FEAT] Task viewing

### ISSUE THREAD

**Issue by El3ctricFX** [dooit-org/dooit#218]
## Viewing current task

Whenever i'm making a new task and the screen is full already with task above i wont be able to see what i'm currently typing.

## Describe the solution you'd like

Make it so whenever the preview is full it follows along with the task i'm typing at that moment so that we don't have scroll then type

**Comment by kraanzu** [comment]
Nice catch. Pushing a patch :)

**Comment by El3ctricFX** [comment]
when do you plan on merging the dev branch just out of curiosity?

**Comment by kraanzu** [comment]
Hi. I was going to merge tomm but got caught up in something else. I'll do it now

**Comment by El3ctricFX** [comment]
just something else to add, the linux-dooit file within releases works fine for me but on the AUR it now says the following and when i try to install the updated version with pacman as well im not able to.

![image](https://github.com/user-attachments/assets/f427d337-52f1-4a17-bc2f-27792651cf20)

![image](https://github.com/user-attachments/assets/9bbbf09c-00e5-481f-b3b4-daa4fad3acbf)


even on the AUR "Python-textual" only goes up to 0.86.3-1

![image](https://github.com/user-attachments/assets/34ffb65c-bb86-463b-b25f-4136a4344901)

**Comment by kraanzu** [comment]
Pushed a fix. Thanks :)
