### ISSUE TITLE
[BUG] dooit command not found

### ISSUE THREAD

**Issue by TakshPanchal** [dooit-org/dooit#22]
**Describe the bug** 🐛
I am unable to open app when I write `dooit` command in the terminal
**To Reproduce** 🐣
1. Install using this command
`python -m pip install git+https://github.com/kraanzu/dooit.git`
2. use `dooit` command

**Expected behavior**  🤔 
App should open when I type the command
**Screenshots** 🧐
![image](https://user-images.githubusercontent.com/52617262/174629095-26e28882-f358-4532-acc8-423fd98c7a8e.png)

**Desktop (please complete the following information):**  🤖
 - OS: Ubuntu 
 - Version 22.04 LTS

**Comment by kraanzu** [comment]
Doesn't look it installed properly
See this: ![image](https://user-images.githubusercontent.com/97718086/174636432-6cadda35-67d5-4092-aca5-d58d2df2c934.png)
